[package]
name = "theemer-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
image = {version = "0.25.10", default-features = false, features = ["jpeg", "png", "webp"]}
lab = "0.11.0"

[profile.release]
lto = "fat"
codegen-units = 1   
strip = true

[profile.dev]
debug="line-tables-only"
